apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: ops
spec:
  containers:
  - name: app1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "jenkins-agent"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - jenkins-agent
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim
